//
//  LicenseViewController.m
//  MTS Notify
//
//  Created by Justin Owens on 1/16/15.
//  Copyright (c) 2015 VisionCPS. All rights reserved.
//

#import "LicenseViewController.h"

@interface LicenseViewController ()


@end

@implementation LicenseViewController

- (void)viewDidLoad {
    [super viewDidLoad];
    
   
    NSString *eula = [NSString stringWithFormat:@"MTS Notify x.x.x\n"
                      "Copyright (c) 2015 Vision\n"
                      "Computer Programming\n"
                      "Services, Inc.\n\n"
                      "*** END USER LICENSE\n"
                      "AGREEMENT ***\n\n"
                      "MPORTANT: PLEASE READ\n"
                      "THIS LICENSE CAREFULLY\n"
                      "BEFORE USING THIS\n"
                      "SOFTWARE.\n\n"
                      "1. LICENSE\n\n"
                      "By receiving, opening the\n"
                      "file package, and/or using\n"
                      "MTS Notify x.x.x(\"Software\")\n"
                      "containing this software,\n"
                      "you agree that this\n"
                      "End User User License\n"
                      "Agreement(EULA) is a\n"
                      "legally binding and valid\n"
                      "contract and agree to be\n"
                      "bound by it. You agree to\n"
                      "abide by the intellectual\n"
                      "property laws and all of\n"
                      "the terms and conditions\n"
                      "of this Agreement.\n\n"
                      "Unless you have a different\n"
                      "license agreement signed\n"
                      "by Vision Computer\n"
                      "Programming Services, Inc.\n"
                      "your use of MTS Notify x.x.x\n"
                      "indicates your acceptance of\n"
                      "this license agreement and\n"
                      "warranty.\n\n"
                      "Subject to the terms of\n"
                      "this Agreement, Vision\n"
                      "Computer Programming\n"
                      "Services, Inc. grants to you a\n"
                      "limited, non-exclusive,\n"
                      "non-transferable license,\n"
                      "without right to sub-license,\n"
                      "to use MTS Notify x.x.x in\n"
                      "accordance with this\n"
                      "Agreement and any other\n"
                      "written agreement with\n"
                      "Vision Computer\n"
                      "Programming Services,\n"
                      "Inc.. Vision Computer not\n"
                      "transfer the title of\n"
                      "MTS Notify x.x.x to you;\n"
                      "the license granted to\n"
                      "you is not a sale. This\n"
                      "agreement is a binding legal\n"
                      "agreement between Vision\n"
                      "Computer Programming\n"
                      "Services, Inc. and the\n"
                      "purchasers or users of\n"
                      "MTS Notify x.x.x.\n\n"
                      "If you do not agree to be\n"
                      "bound by this agreement,\n"
                      "remove MTS Notify x.x.x from\n"
                      "your computer or device now\n"
                      "and, if applicable, promptly\n"
                      "return to Vision Computer\n"
                      "Programming Services, Inc.\n"
                      "by mail any copies of\n"
                      "MTS Notify x.x.x and related\n"
                      "documentation and packaging\n"
                      "in your possession.\n\n"
                      "2. DISTRIBUTION\n\n"
                      "MTS Notify x.x.x and the\n"
                      "license herein granted shall\n"
                      "not be copied, shared,\n"
                      "distributed, re-sold, offered\n"
                      "for re-sale, transferred or\n"
                      "sub-licensed in whole or in\n"
                      "part except that you may\n"
                      "make one copy for archive\n"
                      "purposes only. For information\n"
                      "about redistribution of\n"
                      "MTS Notify x.x.x contact\n"
                      "Vision Computer\n"
                      "Programming Services,\n"
                      "Inc..\n\n"
                      "3. USER AGREEMENT\n\n"
                      "3.1 Use\n\n"
                      "Your license to use\n"
                      "MTS Notify x.x.x is limited to\n"
                      "the number of licenses\n"
                      "purchased by you. You shall\n"
                      "not allow others to use, copy\n"
                      "or evaluate copies of\n"
                      "MTS Notify x.x.x.\n\n"
                      "3.2 Use Restrictions\n\n"
                      "You shall use MTS Notify x.x.x\n"
                      "in compliance with all\n"
                      "applicable laws and not for\n"
                      "any unlawful purpose. Without\n"
                      "limiting the foregoing, use,\n"
                      "display or distribution of\n"
                      "MTS Notify x.x.x together\n"
                      "with material that is\n"
                      "pornographic, racist, vulgar,\n"
                      "obscene, defamatory, libelous,\n"
                      "abusive, promoting hatred,\n"
                      "discriminating or displaying\n"
                      "prejudice based on religion,\n"
                      "ethnic heritage, race, sexual\n"
                      "orientation or age is strictly\n"
                      "prohibited.\n\n"
                      "Each licensed copy of\n"
                      "MTS Notify x.x.x may be used\n"
                      "on one single computer\n"
                      "location by one user, or by\n"
                      "a single group of devices\n"
                      "bound to an Apple iTunes\n"
                      "account, or a single group\n"
                      "of devices bound to a\n"
                      "Google Play Store account.\n"
                      "Use of MTS Notify x.x.x\n"
                      "means that you have loaded,\n"
                      "installed, or run\n"
                      "MTS Notify x.x.x on a\n"
                      "computer or similar device.\n\n"
                      "Other users may not use\n"
                      "your copy of MTS Notify x.x.x.\n"
                      "The assignment, sublicense,\n"
                      "networking, sale, or\n"
                      "distribution of copies of\n"
                      "MTS Notify x.x.x are\n"
                      "strictly forbidden without\n"
                      "the prior written consent\n"
                      "of Vision Computer\n"
                      "Programming Services, Inc..\n"
                      "It is a violation of this\n"
                      "agreement to assign, sell,\n"
                      "share, loan, rent, lease,\n"
                      "borrow, network or\n"
                      "transfer the use of\n"
                      "MTS Notify x.x.x. If any\n"
                      "person other than yourself\n"
                      "uses MTS Notify x.x.x\n"
                      "registered in your name,\n"
                      "regardless of whether it is\n"
                      "at the same time or\n"
                      "different times, then this\n"
                      "agreement is being\n"
                      "violated and you are\n"
                      "responsible for that\n"
                      "violation.\n\n"
                      "3.3 Copyright Restriction\n\n"
                      "This Software contains\n"
                      "copyrighted material, trade\n"
                      "secrets and other proprietary\n"
                      "material. You shall not, and\n"
                      "shall not attempt to, modify,\n"
                      "reverse engineer, disassemble\n"
                      "or decompile\n"
                      "MTS Notify x.x.x. Nor can\n"
                      "you create any derivative\n"
                      "works or other works that\n"
                      "are based upon or\n"
                      "derived from\n"
                      "MTS Notify x.x.x in whole\n"
                      "or in part.\n\n"
                      "Vision Computer\n"
                      "Programming Services, Inc.'s\n"
                      "name, logo and graphics file\n"
                      "that represents\n"
                      "MTS Notify x.x.x shall not be\n"
                      "used in any way to promote\n"
                      "products developed with\n"
                      "MTS Notify x.x.x .\n"
                      "Vision Computer\n"
                      "Programming Services, Inc.\n"
                      "retains sole and exclusive\n"
                      "ownership of all right, title\n"
                      "and interest in and to\n"
                      "MTS Notify x.x.x and all\n"
                      "Intellectual Property rights\n"
                      "relating thereto.\n\n"
                      "Copyright law and\n"
                      "international copyright treaty\n"
                      "provisions protect all parts of\n"
                      "MTS Notify x.x.x, products\n"
                      "and services. No program,\n"
                      "code, part, image, audio\n"
                      "sample, or text may be copied\n"
                      "or used in any way by the\n"
                      "user except as intended\n"
                      "within the bounds of the\n"
                      "single user program. All\n"
                      "rights not expressly\n"
                      "granted hereunder are\n"
                      "reserved for Vision\n"
                      "Computer Programming\n"
                      "Services, Inc..\n\n"
                      "3.4 Limitation of Responsibility\n\n"
                      "You will indemnify, hold\n"
                      "harmless, and defend\n"
                      "Vision Computer\n"
                      "Programming Services, Inc.\n"
                      ", its employees, agents and\n"
                      "distributors against any and\n"
                      "all claims, proceedings,\n"
                      "demand and costs resulting\n"
                      "from or in any way\n"
                      "connected with your use of\n"
                      "Vision Computer\n"
                      "Programming Services,\n"
                      "Inc.'s Software.\n\n"
                      "In no event (including,\n"
                      "without limitation, in the\n"
                      "event of negligence) will\n"
                      "Vision Computer\n"
                      "Programming Services, Inc.\n"
                      ", its employees, agents or\n"
                      "distributors be liable for\n"
                      "any consequential,\n"
                      "incidental, indirect,\n"
                      "special or punitive damages\n"
                      "whatsoever (including,\n"
                      "without limitation, damages\n"
                      "for loss of profits, loss of\n"
                      "use, business interruption,\n"
                      "loss of information or data,\n"
                      "or pecuniary loss), in\n"
                      "connection with or arising\n"
                      "out of or related to this\n"
                      "Agreement, MTS Notify x.x.x\n"
                      "or the use or inability to\n"
                      "use MTS Notify x.x.x or the\n"
                      "furnishing, performance or\n"
                      "use of any other matters\n"
                      "hereunder whether based\n"
                      "upon contract, tort or any\n"
                      "other theory including\n"
                      "negligence.\n\n"
                      "Vision Computer\n"
                      "Programming Services, Inc.'s\n"
                      "entire liability, without\n"
                      "exception, is limited to\n"
                      "the customers'\n"
                      "reimbursement of the\n"
                      "purchase price of the\n"
                      "Software (maximum being\n"
                      "the lesser of the amount\n"
                      "paid by you and the\n"
                      "suggested retail price as\n"
                      "listed by Vision\n"
                      "Computer Programming\n"
                      "Services, Inc. )\n"
                      "in exchange for the\n"
                      "return of the product,\n"
                      "all copies, registration\n"
                      "papers and manuals, and\n"
                      "all materials that\n"
                      "constitute a transfer of\n"
                      "license from the\n"
                      "customer back to\n"
                      "Vision Computer\n"
                      "Programming Services, Inc..\n\n"
                      "3.5 Warranties\n\n"
                      "Except as expressly stated in\n"
                      "writing, Vision\n"
                      "Computer Programming\n"
                      "Services, Inc. makes no\n"
                      "representation or warranties\n"
                      "in respect of this\n"
                      "Software and expressly\n"
                      "excludes all other\n"
                      "warranties, expressed or\n"
                      "implied, oral or written,\n"
                      "including, without\n"
                      "limitation, any implied\n"
                      "warranties of merchantable\n"
                      "quality or fitness for\n"
                      "a particular purpose.\n\n"
                      "3.6 Governing Law\n\n"
                      "This Agreement shall be\n"
                      "governed by the law of\n"
                      "the United States applicable\n"
                      "therein. You hereby\n"
                      "irrevocably attorn and submit\n"
                      "to the non-exclusive\n"
                      "jurisdiction of the courts of\n"
                      "United States therefrom.\n"
                      "If any provision shall be\n"
                      "considered unlawful, void\n"
                      "or otherwise unenforceable,\n"
                      "then that provision shall\n"
                      "be deemed severable from\n"
                      "this License and not\n"
                      "affect the validity and\n"
                      "enforceability of any\n"
                      "other provisions.\n\n"
                      "3.7 Termination\n\n"
                      "Any failure to comply with the\n"
                      "terms and conditions of this\n"
                      "Agreement will result in\n"
                      "automatic and immediate\n"
                      "termination of this license.\n"
                      "Upon termination of this\n"
                      "license granted herein for\n"
                      "any reason, you agree to\n"
                      "immediately cease use of\n"
                      "MTS Notify x.x.x and destroy\n"
                      "all copies of\n"
                      "MTS Notify x.x.x supplied\n"
                      "under this Agreement.\n"
                      "The financial obligations\n"
                      "incurred by you shall survive\n"
                      "the expiration or\n"
                      "termination of this\n"
                      "license.\n\n"
                      "4. DISCLAIMER OF\n"
                      "WARRANTY\n\n"
                      "THIS SOFTWARE AND \n"
                      "THE ACCOMPANYING FILES\n"
                      "ARE SOLD \"AS IS\" AND\n"
                      "WITHOUT WARRANTIES AS\n"
                      "TO PERFORMANCE OR\n"
                      "MERCHANTABILITY OR ANY\n"
                      "OTHER WARRANTIES\n"
                      "WHETHER EXPRESSED OR\n"
                      "IMPLIED. THIS DISCLAIMER\n"
                      "CONCERNS ALL FILES\n"
                      "GENERATED AND EDITED BY\n"
                      "MTS Notify x.x.x AS WELL.\n\n"
                      "5. CONSENT OF USE OF\n"
                      "DATA\n\n"
                      "You agree that Vision\n"
                      "Computer Programming\n"
                      "Services, Inc. may collect\n"
                      "and use information\n"
                      "gathered in any manner as\n"
                      "part of the product\n"
                      "support services provided\n"
                      "to you, if any, related\n"
                      "to MTS Notify x.x.x.\n"
                      "Vision Computer\n"
                      "Programming Services, Inc.\n"
                      "may also use this\n"
                      "information to provide\n"
                      "notices to you which\n"
                      "may be of use or interest\n"
                      "to you.\n\n"
                      ];
    NSString *moreEula = [NSString stringWithFormat:@"6. PRIVACY POLICY AND\n"
                          "INFORMATION SHARING\n\n"
                          "We do not share personal\n"
                          "information with companies,\n"
                          "organizations and individuals\n"
                          "outside of Vision\n"
                          "Computer Programming\n"
                          "Services, Inc. and its\n"
                          "partners and affiliates.\n"
                          "Notifications and messages\n"
                          "sent using\n"
                          "MTS Notify x.x.x are\n"
                          "transferred via SSL encryption.\n\n"
                          "6.1 Third Party Disclosure\n\n"
                          "We do not sell, trade, or\n"
                          "otherwise transfer to\n"
                          "outside parties your\n"
                          "personally identifiable\n"
                          "information unless we\n"
                          "provide you with advance\n"
                          "notice.  This does not\n"
                          "include website hosting\n"
                          "partners who assist us\n"
                          "in operating our website\n"
                          "or apps, conducting business,\n"
                          "or servicing you, so long\n"
                          "as those parties agree\n"
                          "to keep this information\n"
                          "confidential.  We may also\n"
                          "release your information\n"
                          "when we believe it is\n"
                          "necessary and appropriate\n"
                          "to comply with the law,\n"
                          "enforce our site\n"
                          "policies, or protect\n"
                          "our or others' rights,\n"
                          "property, or safety.\n\n"
                          "6.2 Fair Information Practices\n\n"
                          "The Fair Information\n"
                          "Practices Principles form\n"
                          "the backbone of privacy\n"
                          "law in the United\n"
                          "States and the concepts\n"
                          "they include have\n"
                          "played a significant role\n"
                          "in the development of\n"
                          "data protection laws\n"
                          "around the globe.\n"
                          "Understanding the Fair\n"
                          "Information Practice\n"
                          "Principles and how they\n"
                          "should be implemented is\n"
                          "critical to comply with\n"
                          "the various privacy laws\n"
                          "that protect personal\n"
                          "information.\n\n"
                          "In order to be in line\n"
                          "with Fair Information\n"
                          "Practices we will take\n"
                          "the following responsive action,\n"
                          "should a data breach occur\n"
                          "we will notify the users\n"
                          "via email within 7 business\n"
                          "days.\n\n"];
    
    self.eulaLabel.text = eula;
    self.otherLabel.text = moreEula;
}

- (void)didReceiveMemoryWarning {
    [super didReceiveMemoryWarning];
    // Dispose of any resources that can be recreated.
}



/*
#pragma mark - Navigation

// In a storyboard-based application, you will often want to do a little preparation before navigation
- (void)prepareForSegue:(UIStoryboardSegue *)segue sender:(id)sender {
    // Get the new view controller using [segue destinationViewController].
    // Pass the selected object to the new view controller.
}
*/

@end
